name = "trac-nghiem-online"
main = "src/index.js"
compatibility_date = "2024-03-01"

# Cấu hình thư mục chứa file tĩnh (HTML, JSON)
[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
